=== skh/swamp/conf/dtds/workflow.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT workflow (metadata, node+, dataset)>
<!ATTLIST workflow 	name	    	ID 	#REQUIRED
				  	version	    	CDATA 	#REQUIRED
				  	leastSWAMPVersion 	CDATA 	#REQUIRED
				  	parentwf 	    CDATA 	#IMPLIED
				  	parentwfversion	CDATA 	#IMPLIED>


<!ELEMENT metadata 	(templatedescription, description, helpcontext?, creator?, 
					history?, roles)>
<!ELEMENT templatedescription 	(#PCDATA)>
<!ELEMENT description 	(#PCDATA)>
<!ELEMENT creator 	(#PCDATA)>
<!ELEMENT history 	(change+)>
<!ELEMENT change 	(#PCDATA)>
<!ATTLIST change    who         CDATA   #REQUIRED
                    when        CDATA   #REQUIRED>              

<!ELEMENT roles (role+)>
<!ELEMENT role (description?,rolevalue*)>
<!ATTLIST role name CDATA #REQUIRED
		       restricted (true|false)   #REQUIRED
		       type (databit|value|reference|dbreference) #IMPLIED>
<!ELEMENT rolevalue 	(#PCDATA)>


<!ELEMENT node  (description, longdesc?, helpcontext?, milestone?, duedate?, 
(dataedit|manualtask|decision|notification|customtask|startsubworkflow|sendevent|scriptaction)*, edge*)>
<!ATTLIST node name		ID     		   #REQUIRED
               type		(start|end)    #IMPLIED>


<!ELEMENT milestone (description?)>
<!ATTLIST milestone   name        ID    	#REQUIRED
					weight      CDATA    	#IMPLIED>

<!ELEMENT duedate EMPTY>
<!ATTLIST duedate databit CDATA #REQUIRED>

<!ELEMENT edge (event|data|subsfinished|and|not|or)*>
<!ATTLIST edge to           IDREF     #REQUIRED
               event        CDATA     #IMPLIED>

<!ELEMENT event (#PCDATA)>
<!ATTLIST event type       CDATA     #REQUIRED>

<!ELEMENT data EMPTY>
<!ATTLIST data field	CDATA	  #REQUIRED
	           check	(regexp|changed)  #REQUIRED
	           value	CDATA	  #IMPLIED>
	           
<!ELEMENT subsfinished EMPTY>
<!ATTLIST subsfinished subname CDATA #REQUIRED>
<!ATTLIST subsfinished subversion CDATA #REQUIRED>

<!ELEMENT not (event|data|not|or|and|subsfinished)>

<!ELEMENT or  ((event|data|not|or|and|subsfinished),(event|data|not|or|and|subsfinished))>

<!ELEMENT and ((event|data|not|or|and|subsfinished),(event|data|not|or|and|subsfinished))>

<!ELEMENT longdesc (#PCDATA)>
<!ELEMENT helpcontext (#PCDATA)>


<!ELEMENT manualtask (description, longdesc?, helpcontext?)>
<!ATTLIST manualtask name       	ID       #REQUIRED
		             role			CDATA	#IMPLIED
		             eventtype	CDATA	#REQUIRED
		             notificationtemplate	CDATA	#IMPLIED
		             mandatory	(true|false)	#IMPLIED
		             restricted	(true|false)	#IMPLIED>

<!ELEMENT decision (description, longdesc?, helpcontext?, question, answer+)>
<!ATTLIST decision name			ID	#REQUIRED
		           role			CDATA	#IMPLIED
		           notificationtemplate	CDATA	#IMPLIED
		           mandatory	(true|false)	#IMPLIED
		           restricted	(true|false)	#IMPLIED>

<!ELEMENT question (#PCDATA)>

<!ELEMENT answer (#PCDATA)>
<!ATTLIST answer eventtype	CDATA	#REQUIRED>

<!ELEMENT dataedit (description, longdesc?, helpcontext?, field+, script?)>
<!ATTLIST dataedit name         	ID   	#REQUIRED
                   role		     CDATA	#IMPLIED
                   eventtype    	CDATA   	#REQUIRED
                   notificationtemplate	CDATA	#IMPLIED
                   mandatory	(true|false)	#IMPLIED
                   restricted	(true|false)	#IMPLIED>

<!ELEMENT field EMPTY>
<!ATTLIST field path	CDATA	#REQUIRED
		mandatory	    (true|yes|false|no)	#REQUIRED>


<!ELEMENT notification (recipient, description?)+>
<!ATTLIST notification    	name 		ID		#REQUIRED
							msgtemplate	CDATA	#IMPLIED 
			             	msgtext		CDATA	#IMPLIED>
			
<!ELEMENT recipient EMPTY>
<!ATTLIST recipient	dbit      		CDATA   #IMPLIED
			        recipientname   CDATA   #IMPLIED
			        recipientemail	CDATA   #IMPLIED
			        recipientrole  	CDATA   #IMPLIED>


<!ELEMENT customtask (description)>
<!ATTLIST customtask name         ID    #REQUIRED
                     eventtype    CDATA    #REQUIRED
                     class        CDATA    #REQUIRED
                     function     CDATA    #REQUIRED>  
                     
<!ELEMENT scriptaction (description, script)>
<!ATTLIST scriptaction name         ID    #REQUIRED>
<!ELEMENT script (#PCDATA)>
<!ATTLIST script language     CDATA #IMPLIED>


<!ELEMENT startsubworkflow (description)>
<!ATTLIST startsubworkflow 	name			  ID		  #REQUIRED
							subname		  CDATA    #REQUIRED
						 	subversion	  CDATA    #REQUIRED>  


<!ELEMENT sendevent (description?, triggerdate?, targetwfs?)>
<!ATTLIST sendevent    name    ID    #REQUIRED 
					   eventtype CDATA #REQUIRED> 

<!ELEMENT triggerdate (#PCDATA)>
<!ATTLIST triggerdate    databit CDATA    #REQUIRED
						 offset  CDATA    #REQUIRED
					     onlyweekdays (true|false) #IMPLIED> 

<!ELEMENT targetwfs (#PCDATA)>

<!ELEMENT dataset   (dataset|databit)*>
<!ATTLIST dataset    name           CDATA #REQUIRED
                     description    CDATA #REQUIRED
                     state ( hidden | read-only | read-write ) #IMPLIED>

<!ELEMENT databit    (description?,longdesc?,defaultvalue?,dbedit?,value*)>
<!ATTLIST databit   name          CDATA    #REQUIRED
					shortdesc     CDATA 	#IMPLIED
					description   CDATA 	#IMPLIED
					type          CDATA 	#REQUIRED
					state ( hidden | read-only | read-write ) #IMPLIED>


<!ELEMENT defaultvalue (#PCDATA)>


<!ELEMENT dbedit EMPTY>
<!ATTLIST dbedit type (list|text|select|checkbox) #REQUIRED
                 xsize CDATA #IMPLIED
		         ysize CDATA #IMPLIED>


<!-- values of enum lists -->
<!ELEMENT value (#PCDATA)>
<!ATTLIST value type CDATA 	 #REQUIRED>

=== skh/swamp/conf/workflows/rating/1.0/workflow.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE workflow SYSTEM "../../../../../swamp/swamp/conf/dtds/workflow.dtd">
<workflow name="rating" 
          version="1.0" 
          leastSWAMPVersion="1.6" 
          parentwf="application" 
          parentwfversion="1.0">

    <metadata>
      <templatedescription>
      	Workflow to track a rating of a Job-Application
      </templatedescription>
      <description>Rating from $wf.getDatabitValue("bewertungsdata.bewerterdata.name"): 
      	#if (!$wf.getDatabitValue("bewertungsdata.bewerterdata.result").equals(""))
      	($wf.getDatabitValue("bewertungsdata.bewerterdata.result"))
      	#elseif($wf.getNode("theend").isActive())
      	(canceled)
      	#else 
      	(to be rated)
      	#end
      	#if (${wf.getDatabitValue("bewertungsdata.bewerterdata.comment").length()} > 60)
      		${wf.getDatabitValue("bewertungsdata.bewerterdata.comment").substring(0,60)}...
      	#else 
      		${wf.getDatabitValue("bewertungsdata.bewerterdata.comment")}
      	#end
      </description>
      <creator>tschmidt</creator>
      
      	<history>
        <change who="tschmidt" when="2005-06-20">Version 0.1</change>
        </history>
      
		<roles>
			<role name="admin" restricted="true" type="reference">
				<description>JobTracker admins</description>
				<rolevalue>parent.admin</rolevalue>
			</role>

			<role name="starter" restricted="true" type="reference">
				<rolevalue>parent.user</rolevalue>
			</role>
			<role name="user" restricted="true" type="reference">
				<rolevalue>parent.user</rolevalue>
			</role>
			<role name="owner" restricted="true" type="databit">
				<rolevalue>bewertungsdata.roles.owner</rolevalue>
			</role>
			<role name="bewerter" restricted="true" type="databit">
				<rolevalue>bewertungsdata.bewerterdata.name</rolevalue>
			</role>
		</roles>
    </metadata>



   <node type="start" name="bewertung_start">
    	<description>Start Rating</description>

	<dataedit role="bewerter" name="rate" eventtype="RATED" 
		notificationtemplate="notifications/please_rate" restricted="true">
		<description>Please rate the application of 
			$wf.getDatabitValue("bewerbungsdata.bewerberdata.name")</description>	
		<longdesc>
		#set ($htmlout = "true")
		#showdata ($wf "bewerbungsdata.bewerberdata.name")
		#showdata ($wf "ausschreibungsdata.stelle")
		#showdata ($wf "bewerbungsdata.bewerberdata.eingang_am")
		#showdata ($wf "bewerbungsdata.bewerterdata.request_comment")
		
		#if (!$wf.getDatabitValue("bewerbungsdata.files.file1").equals("") || !$wf.getDatabitValue("bewerbungsdata.files.file2").equals("") || !$wf.getDatabitValue("bewerbungsdata.files.file3").equals("") || !$wf.getDatabitValue("bewerbungsdata.files.file4").equals(""))	
		Files: \n
		#showdata ($wf "bewerbungsdata.files.file1")
		#showdata ($wf "bewerbungsdata.files.file2")
		#showdata ($wf "bewerbungsdata.files.file3")
		#showdata ($wf "bewerbungsdata.files.file4")
		#end
		</longdesc>
		<field mandatory="true" path="bewertungsdata.bewerterdata.result"></field>
		<field mandatory="true" path="bewertungsdata.bewerterdata.comment"></field>
	</dataedit>
	
   <edge to="announce_finish" event="RATED" />
   <edge to="announce_finish">
		<data check="regexp" field="bewertungsdata.bewerterdata.result" value=".+" /> 
   </edge>
   <edge to="theend" event="BEWERBUNG_FINISHED" />
   <edge to="theend" event="PARENTWORKFLOW_FINISHED" />
   </node>
   
		
		
	<node name="announce_finish">
		<description>
		Announcing Rating finished
		</description>
		<notification name="announce_finish_mail" msgtemplate="notifications/announce_finish">
			<recipient dbit="ausschreibungsdata.roles.abtleiter"/>
		</notification>
		
		<scriptaction name="set_rater">
			<description>Check if user was the supposed rater</description>
			<script>
				$wf.getDatabit("bewertungsdata.bewerterdata.name").setValue($uname)
			</script>
		</scriptaction>
		
		<edge to="theend" event="none"/>
	</node>
		
		
	<!-- ############## End Nodes ################## -->		
			
    <node type="end" name="theend">
      <description>Rating finished</description>
      <longdesc>
      #if (!$wf.getDatabitValue("bewertungsdata.bewerterdata.result").equals(""))
      Rating of $wf.getDatabitValue("bewertungsdata.bewerterdata.name"):  
      $wf.getDatabitValue("bewertungsdata.bewerterdata.result") \n
      Comment: \n
      $wf.getDatabitValue("bewertungsdata.bewerterdata.comment")
      #end
      </longdesc>
    </node>

    
	<!-- ##################  Datapack starts here #################### -->
    
    <dataset name="bewertungsdata" description="Data for this Rating">

    <!-- Values will be copied in from the Bewerbungs Workflow -->
    <dataset description="Evaluator-Data" name="bewerterdata" state="read-write">
    
		 <databit name="name" description="Name of the Evaluator (Login)" type="person"/>
		 
		 <databit name="request_comment" description="comment from requester" type="text" state="read-only"/>
		 
		 <databit name="result" description="Result of the Rating" type="enum">
			<defaultvalue></defaultvalue>
			<value type="string"></value>
			<value type="string">not rated</value>
			<value type="string">--</value>
			<value type="string">-</value>
			<value type="string">o</value>
			<value type="string">+</value>
			<value type="string">++</value>
		 </databit>
		 <databit type="text" name="comment" description="additional comment" state="read-write">
		 	<dbedit type="text" xsize="65" ysize="7"/>
		 </databit>
	</dataset>
	
	<dataset description="Roles" name="roles" state="hidden">
		 <databit name="owner" description="Owner" type="person" state="hidden"/>
	</dataset>
	
    </dataset>
</workflow>

=== skh/swamp/conf/workflows/ExampleSub/0.1/workflow.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE workflow SYSTEM "../../../dtds/workflow.dtd">
<workflow name="ExampleSub" 
          version="0.1" 
          leastSWAMPVersion="1.5.4"
          parentwf="Example"
          parentwfversion="0.2">

	<metadata>
		<templatedescription>Workflow for testing subworkflows</templatedescription>
		<description>Workflow for testing subworkflows</description>
		<creator>Thomas Schmidt</creator>
		
		<roles>
			<role name="owner" restricted="true" type="databit">
				<rolevalue>testdataset.roles.owner</rolevalue>
			</role>
			<role name="admin" restricted="true">
				<description>Admins</description>
				<rolevalue>swamp_admin</rolevalue>
			</role>
			<role name="starter" restricted="true">
				<description>Who can start an example workflow</description>
				<rolevalue>swamp_user</rolevalue>
			</role>
			<role name="user" restricted="false" type="databit">
				<rolevalue>testdataset.roles.user</rolevalue>
			</role>
		</roles>
			
	</metadata>


	<!-- node start -->
	<node type="start" name="start">
	<description>Startnode</description>
		<manualtask name="sub1_task" eventtype="sub1_task_done">
			<description>SUBWORKFLOW TASK</description>
		</manualtask>
	
	<edge to="tmp" event="sub1_task_done"/>
	<!-- handle standard event -->
	<edge to="end" event="PARENTWORKFLOW_FINISHED"/>
	</node>
	
	
	<node name="tmp">
	<description>TMP node</description>
	<!-- DATA Edit -->
	<dataedit name="flag_edit" eventtype="set_flag">
	<description>Editing a databit of the parents workflow</description>
	
	<!-- Fields... -->
	<field path="testdataset.flag" mandatory="yes" />
	</dataedit>
	
	<edge to="end">
	<data check="regexp" field="testdataset.flag" value="true"/>
	</edge>
	
	</node>
	
	
	<!-- node END -->
	<node type="end" name="end">
	<description>Subworkflow is finished</description>
	</node>
    
    
    <dataset name="subtestdataset" description="Dataset for Subworkflow">
    </dataset>
    
</workflow>

=== skh/swamp/conf/workflows/minimal_test/0.1/workflow.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE workflow SYSTEM "../../../dtds/workflow.dtd">
<workflow name="minimal_test" version="0.1" leastSWAMPVersion="1.4">

	<metadata>
		<templatedescription>
		Test for a abolute minimal workflow definition. \n
		Taking this template is a good starting point to develop 
		your workflow. 
		</templatedescription>
		<description>Minimal Workflow</description>
		
		<roles>
			<role name="owner" restricted="false" type="databit">
				<rolevalue>testdataset.owner</rolevalue>
			</role>
			<role name="admin" restricted="false"/>
			<role name="starter" restricted="false"/>
			<role name="user" restricted="false"/>
		</roles>
	</metadata>


	<node type="start" name="start">
		<description>Startnode</description>
		<edge to="end" event="none"/>
	</node>


    <node type="end" name="end">
		<description>Endnode reached</description>
    </node>
    
    
    
	<!--  attached data of the workflow -->
	
    <dataset name="testdataset" description="minimal dataset">
		<databit name="owner" type="person" />
    </dataset>


</workflow>

=== skh/swamp/conf/workflows/Example/0.1/workflow.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE workflow SYSTEM "../../../dtds/workflow.dtd">
<workflow name="Example" 
          version="0.1" 
          leastSWAMPVersion="1.5.4" 
          parentwf="Example" 
          parentwfversion="0.1">

	<metadata>
		<templatedescription>Workflow for Testing Issues</templatedescription>
		<description>Workflow for Testing Issues</description>
		<creator>Thomas Schmidt</creator>
		<history>
		<change who="tschmidt" when="2004-10-27">Creation</change>
		</history>
		
		<roles>
			<role name="owner" restricted="true" type="databit">
				<rolevalue>testdataset.roles.owner</rolevalue>
			</role>
			<role name="admin" restricted="true">
				<description>Admins</description>
				<rolevalue>swamp_admin</rolevalue>
			</role>
			<role name="starter" restricted="true" type="databit">
				<rolevalue>testdataset.roles.starter</rolevalue>
			</role>
			<role name="user" restricted="false" type="databit">
				<rolevalue>testdataset.roles.user</rolevalue>
			</role>
		</roles>
			
	</metadata>


	<node type="start" name="start">
	<description>Start node</description>
	<longdesc>long description for that node</longdesc>
	
	<!--  example for a notification task: -->
	<notification name="notify_owner" msgtemplate="notifications/notification1">
		<recipient recipientemail="please_change@swamp.swamp"/>
		<recipient dbit="testdataset.roles.user"/>
		<recipient recipientrole="user"/>
		<recipient recipientname="swamp_user"/>
	</notification>
	
	<edge to="node1" event="none"/>
	</node>

	<node name="node1">
	<description>Example for a DataeditAction</description>
	
	<!--  Example for a dataeditaction -->
	<dataedit name="dataedit" restricted="false" eventtype="DATAEDIT_OK">
		<description>Please fill in the fields.</description>
		<field path="testdataset.product.product_name" mandatory="yes" />
		<field path="testdataset.roles.manualtask_owner" mandatory="yes" />
		<field path="testdataset.duedate1" mandatory="yes" />
	</dataedit>
		
	<!--  Example for Edges with Event-Conditions -->
	<edge to="node2">
		<event type="DATAEDIT_OK" />
	</edge>
	<edge to="node_milestone1" event="DATAEDIT_OK" />
	</node>


	<!--  example for a milestone: -->
	<node name="node_milestone1">
      <description>Milestone 1 reached</description>
      <milestone name="m1" weight="5">
      	<description>Milestone 1 reached</description>
      </milestone>
	</node>




	<node name="node2">
	<description>Example for a Decision</description>
	<duedate databit="testdataset.duedate1"/>
	<decision name="decision">
		<description>Choosing a path</description>
		<question>Please choose a path</question>
		<answer eventtype="PATH1">Take Path 1 in this Workflow.</answer>
		<answer eventtype="PATH2">Take Path 2 in this Workflow.</answer>
		<answer eventtype="PATH3">Take Path 3 in this Workflow. 
			(includes starting a subworkflow)</answer>
		</decision>
		<edge to="path1" event="PATH1" />
		<edge to="path2" event="PATH2" />
		<edge to="path3" event="PATH3" />
	</node>





	<node name="path1">
	<description>Example for a node with a Customtask</description>

	<!--  Example for a custom-task -->
	<customtask name="custom_test" eventtype="none" 
		class="de.suse.swamp.custom.CustomActionExample" 
		function="customTest" >
		<description>Calling de.suse.swamp.custom.CustomActionExample.customTest()</description>
	</customtask>
	
	<edge to="path1-2" event="none" />
	</node>
	
	
	
	
	<node name="path1-2">
	<description>Example for a ManualTask</description>
	
	<!--  example for a scriptaction -->
	<scriptaction name="script_example">
		<description>Setting comment</description>
		<script>
      	$wf.getDatabit("testdataset.comment").setValue("Comment set by scriptaction.")
      	</script>
	</scriptaction>
	
	<manualtask name="manualtask1" eventtype="UNITE">
		<description>Go on in the Workflow</description>
	</manualtask>
	
	<edge to="unite" event="UNITE" />
	</node>


	<node name="path2">
	<description>Example for a ManualTask</description>
	<manualtask name="manualtask2" eventtype="UNITE">
		<description>Go on in the Workflow</description>
	</manualtask>
	
	<!--  example for a sendevent action -->
	<sendevent name="reminder" eventtype="DELAY_1D">
  		<triggerdate databit="System.path2.enterDate" 
  			offset="+1d"
  			onlyweekdays="true"/> 
	</sendevent>
	
	
	<edge to="unite" event="UNITE" />
	<edge to="path2" event="DELAY_1D" />
	<edge to="path2_is_late" >
		<event type="DELAY_1D"/>
	</edge>
	</node>
	
	
	
	<node name="path2_is_late">
	<description>Node path2 is late</description>

	<!-- this node will get activated if "path2" is not left 1 day 
		after it was activated. So we could insert notifications etc. here -->
	</node>
	
	
	
	
	<node name="path3">
	<description>forking subworkflow</description>

	<!--  Example for forking a subworkflow -->
	<startsubworkflow name="startsub" subname="Example" subversion="0.1">
		<description>Starting Subworkflow</description>	
	</startsubworkflow>

	<edge to="path3-2" event="none" />
	</node>



	<node name="path3-2">
	<description>Example for a ManualTask</description>
	<manualtask name="manualtask3" eventtype="UNITE">
		<description>Go on in the Workflow</description>
	</manualtask>
	<edge to="unite" event="UNITE" />
	</node>





	<node name="unite">
	<description>Example for a DataeditTask</description>
		
	<!--  Example for a duedate -->
	<duedate databit="testdataset.duedate1"/>
	
	<dataedit name="dataedit1" eventtype="DATAEDIT2_OK">
		<description>Please fill in the fields.</description>
		<longdesc>Depending on your choice either endnode1 or endnode2 will be entered. \n
		The edges to a regular expression check on the product field. </longdesc>
		<field path="testdataset.product.product_name" mandatory="yes" />
		<field path="testdataset.roles.manualtask_owner" mandatory="yes" />
	</dataedit>

	<edge to="node_milestone2" event="DATAEDIT2_OK" />

	<!--  split the workflow depending on content of testdataset.product.product_name -->
	<edge to="node_product1">
		<data check="regexp" field="testdataset.product.product_name" value=".*SLES.*"/>
	</edge>

	<!--  example for a nested condition (does not really make sense)-->
	<edge to="node_product1">
		<and>
		<event type="DATAEDIT2_OK"/>
		<not>
		<data check="regexp" field="testdataset.product.product_name" value=".*LINUX.*"/>
		</not>
		</and>
	</edge>

	<edge to="node_product2">
		<data check="regexp" field="testdataset.product.product_name" value=".*LINUX.*"/>
	</edge>
	</node>


	<!--  example for a milestone: -->
	<node name="node_milestone2">
      <description>Milestone 2 reached</description>
      <milestone name="m2" weight="15">
      	<description>Milestone 2 reached</description>
      </milestone>
	</node>




	<node name="node_product1">
      <description>Milestone 2 reached</description>

	<edge to="theend2" event="none" />
	</node>



	<node name="node_product2">
      <description>Milestone 2 reached</description>

	<edge to="theend1" event="none" />
	</node>
	




    <node type="end" name="theend1">
      <description>Endnode 1</description>
    </node>


    <node type="end" name="theend2">
      <description>Endnode 2</description>
    </node>
    
    
    
    
    
	<!--  attached data of the workflow -->
    <dataset name="testdataset" description="Core Dataset for Testworkflow">

	<dataset description="Roles" name="roles">
		 
		 <databit name="owner" description="Owner of this Workflow" type="person" 
		 	state="read-write" shortdesc="Owner"/>
		 <databit name="admin" description="Workflow-Admins" type="person" state="read-write">
		 	<defaultvalue>swamp_admin</defaultvalue>
		 </databit>
		 <databit name="starter" description="Who is allowed to start this Workflow" type="person" state="read-write">
		 	<defaultvalue>swamp_user</defaultvalue>
		 </databit>
		 <databit name="user" description="Workflow-Users" type="person" state="hidden"/>
		 		
		 <databit name="manualtask_owner" 
		 description="Who is responsible for the manual Task?" 
		 type="person"/>
	</dataset>
	
		 
	
	<databit name="reason" description="The Reason for this Workflow case" 
		 type="string">
	<defaultvalue>A new year, a new product</defaultvalue>
	</databit>

	<databit name="duedate1" 
		 description="DueDate for 2nd dataedittask" type="date">
	</databit>

	<databit name="comment" 
		 description="Comment to this workflow" type="text">
	</databit>

	<dataset name="product"    
		 description="This Dataset contains product information">

	    <databit name="product_name" 
	             description="The name of the product" type="enum" >
		<defaultvalue >NLD 10</defaultvalue>
		<value type="string">NLD 10</value>
		<value type="string">SUSE LINUX 9.3</value>
		<value type="string">SUSE LINUX 9.2</value>
		<value type="string">SUSE LINUX 10</value>
		<value type="string">SLES 9</value>
		</databit>
		     
		     
		 <dataset name="product_texts"    
		 description="Texts for the product">

	    <databit name="desc" 
	             description="Description Text" 
		     type="text" />
		</dataset>
		     
	</dataset>
	
	
	<dataset name="childset1"    
		 description="child1 of root set">

	    <databit name="bit_child12" 
	             description="bit1 in child set1" 
		     type="number" />
	    <databit name="bit_child22" 
	             description="bit2 in child set1" 
		     type="number" />		
		     
		     
		 <dataset name="childset1-1"    
		 description="child of childset1">

	    <databit name="bit_child2-2-1" 
	             description="bit1 in childset1-1" 
		     type="number" state="read-only" />
	    <databit name="bit_child2-2-2" 
	             description="bit2 in childset1-1" 
		     type="number" state="read-write" />		
		</dataset>
		     
	</dataset>
	

	
    </dataset>
</workflow>
